{{-- Converted from the static site's `pages/terms.js`: the copy is the
    copy, with the Bootstrap wrapper markup dropped and the old `h5`
    sub-headings promoted to `h2`, which is what they always were
    semantically. Nothing here was rewritten — this is a legal page. --}}
<x-site-layout
    title="Terms of Service | 12 Step Toolkit"
    description="The terms that apply when you use the 12 Step Toolkit app and website, including subscriptions, acceptable use and disclaimers."
    :crumbs="['Terms and Conditions' => null]"
>
    <h1>Terms and Conditions</h1>

    <article class="reading prose">
    <p>Last Updated: February 10, 2025</p>
    <p>Welcome to 12StepToolkit! iByte Apps Limited (“iByte Apps”) provides our website located at www.12steptoolkit.com & web.12steptoolkit.com (the “Site”) and our 12 step recovery and self-help services accessible via our Site and our mobile device application (“App”). To make these Terms easier to read, the Site, our services and App are collectively called the “Services.” Please read these Terms of Service (the “Terms”) carefully because they govern your use of our Services.</p>
    <h2>Agreement to Terms</h2>
    <p>By using our Services, you agree to be bound by these Terms. If you don’t agree to be bound by these Terms, DO NOT use the Services.</p>
    <h2>Privacy Policy</h2>
    <p>Please refer to our <a href="/privacy">Privacy Policy</a> for information on how we collect, use and disclose information from our users. You acknowledge and agree that your use of the Services is subject to our Privacy Policy.</p>
    <h2>Changes to Terms or Services</h2>
    <p>We may modify the Terms at any time, in our sole discretion. If we do so, we’ll let you know either by posting the modified Terms on the Site or through other communications. It’s important that you review the Terms whenever we modify them because if you continue to use the Services after we have posted modified Terms on the Site, you are indicating to us that you agree to be bound by the modified Terms. If you don’t agree to be bound by the modified Terms, then you may not use the Services anymore. Because our Services are evolving over time we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.</p>
    <h2>Mediation Notice</h2>
    <p>Unless you opt out of mediation within 30 days of the date you first agree to these terms by following the opt-out procedure specified in the “Mediation” section below, and except for certain types of disputes described in the “Mediation“ section below, you agree that disputes between you and iByte Apps will be resolved by binding, individual mediation and you are waiving your right to a trial by jury or to participate as a claimant or class member in any purported class action or representative proceeding.</p>
    <h2>Eligibility</h2>
    <p>You may use the Services only if you are 18 years or older and are not barred from using the Services under applicable law. To make a purchase via the Services (described in the Section titled “Purchases” below), you must be 18 years or older and capable of forming a binding contract.</p>
    <h2>Registration and Your Information</h2>
    <p>If you want to use certain features of the Services you’ll have to create an account (“Account”). You can do this via the App or the Site or through your account with certain third-party social networking services such as Facebook or Google (each, an “SNS Account”). If you choose the SNS Account option we’ll create your Account by extracting from your SNS Account certain personal information such as your name and email address and other personal information that your privacy settings on the SNS Account permit us to access.</p>
    <p>It’s important that you provide us with accurate, complete and up-to-date information for your Account and you agree to update such information, as needed, to keep it accurate, complete and up-to-date. If you don’t, we might have to suspend or terminate your Account. You agree that you won’t disclose your Account password to anyone and you’ll notify us immediately of any unauthorized use of your Account. You’re responsible for all activities that occur under your Account, whether or not you know about them.</p>
    <h2>Using the Services</h2>
    <p>Via the Services, users can select from a variety of options to create inventories, notes and connections with other users who use our service. You can also use the paid functionality of the Services to utilize the enhanced functionality of the Services or purchase items that are offered for sale through the Services (the “Products”), as described in further detail under the Section titled “Purchases” below.</p>
    <p>You understand and agree that the Services, Products and any other information you learn from iByte Apps are not intended, designed, or implied to diagnose, prevent, or treat any condition or disease, to ascertain the state of your health, or to be a substitute for professional medical care. Not all activities described on the Services or Products are suitable for everyone. You understand and agree that you are solely responsible for your use of the Services.</p>
    <h2>Online Sponsorship</h2>
    <p>Online sponsorship is a new feature introduced in September 2020. This is a sensitive element of the app and must be used with complete responsibility. By agreeing to be an online sponsor or sponsee, you agree to the following</p>
    <li>To provide your genuine phone number to us so that we may authenticate your identity for yours and our other app users’ safety. Your phone number will not be displayed to any other users, but we may send you advertising material from carefully selected third parties if you are not a subscribed user.</li>
    <li>You will provide genuine and truthful information about yourself</li>
    <li>(Sponsors Only) That you have completed your 12 Steps and are thereby able to offer your help to other app users to do the same</li>
    <li>That you will be careful when sharing your personal information such as your phone number, real name, place of residence, etc.</li>
    <li>That if you share your personal information, you will be completely liable for the consequences arising out of such</li>
    <li>That you will not misuse the information shared with you by your sponsor or sponsees</li>
    <li>That you will not hold iByte Apps Limited and any of its employees liable in any way due to any consequences arising out of online sponsorship or any other features of the app.</li>
    <li>(Sponsors Only) That you continue to remain sober throughout the period of sponsoring other people and if you relapse, you shall notify them immediately and will withdraw your sponsorships from your sponsees and will not continue to offer sponsorship to new sponsees</li>
    <h2>Purchases</h2>
    <p>iByte Apps offers certain enhanced features of the Services which you can purchase as a quarterly or yearly(“Subscription”). A description of features associated with Subscriptions is available via the Services. When you purchase a Subscription or a Product (each, a “Transaction”), we may ask you to supply additional information relevant to your Transaction, such as your credit card number, the expiration date of your credit card and your address(es) for billing and delivery (such information, “Payment Information”). You represent and warrant that you have the legal right to use all payment method(s) represented by any such Payment Information. The amounts due and payable by you for a Transaction through the Services will be presented to you before you place your order. If you choose to initiate a Transaction via the Services, you authorize us to provide your Payment Information to third party service providers so we can complete your Transaction and agree (a) to pay the applicable fees and any taxes; (b) that iByte Apps may charge your credit card or third party payment processing account, including, but not limited to, your account with the app store or distribution platform (like the Apple App Store, Google Play or the Amazon Appstore) where the App is made available (each, an “App Provider”), for verification, pre-authorization and payment purposes; and (c) to bear any additional charges that your App Provider, bank or other financial service provider may levy on you as well as any taxes or fees that may apply to your order. You’ll receive a confirmation email after we confirm the payment for your order. Your order is not binding on iByte Apps until accepted and confirmed by iByte Apps. All payments made are non-refundable and non-transferable except as expressly provided in these Terms.</p>
    <p>If you have any concerns or objections regarding charges, you agree to raise them with us first and you agree not to cancel or reject any credit card or third party payment processing charges unless you have made a reasonable attempt at resolving the matter directly with iByte Apps.</p>
    <p>iByte Apps reserves the right to not process or to cancel your order in certain circumstances, for example, if your credit card is declined, if we suspect the request or order is fraudulent, or in other circumstances iByte Apps deems appropriate in its sole discretion. iByte Apps also reserves the right, in its sole discretion, to take steps to verify your identity in connection with your order. You may need to provide additional information to verify your identity before completing your Transaction (such information is included within the definition of Payment Information). iByte Apps will either not charge you or refund the charges for orders that we do not process or cancel.</p>
    <h2>Return Policy</h2>
    <p>iByte Apps offers this app free of cost such that users are able to try it and test it before purchasing. Thereby, all subscriptions are non-refundable unless iByte Apps fails to deliver the promised service. If there is a disruption of service, iByte Apps will be notified as soon as possible and iByte Apps will try and rectify any reported disruption within 48 hours of such notice.</p>
    <p>Subscriptions Automatically Renew Until You Cancel & How to Cancel Your Subscription</p>
    <p>All amounts are payable and charged: (i) for one-off purchase (e.g. lifetime Subscription), at the time you place your order; and (ii) For quarterly or yearly subscriptions, at the beginning of the subscription and, because each such subscription renews automatically for an additional period equal in length to the expiring subscription term until you cancel it, at the time of each renewal until you cancel, using the Payment Information you have provided. You must cancel your quarterly or yearly Subscription before it renews to avoid the billing of the fees for the next Subscription period. If you purchase your Subscription via the Site, you can cancel the renewal of your subscription at any time by contacting us by email at info@12steptoolkit.com. If you purchase your Subscription via an App Provider, you can cancel the renewal of your subscription at any time with the App Provider. You will not receive a refund for the fees you already paid for your current subscription period and you will continue to receive the Services ordered until the end of your current Subscription period.</p>
    <h2>Changes to Price Terms for Subscriptions</h2>
    <p>iByte Apps reserves the right to change its pricing terms for Subscriptions at any time and iByte Apps will notify you in advance of such changes becoming effective. Changes to the pricing terms will not apply retroactively and will only apply for Subscription renewals after such changed pricing terms have been communicated to you. If you do not agree with the changes to iByte Apps’s pricing terms then you may choose not to renew your Subscription in accordance with the section “Subscriptions Automatically Renew Until You Cancel & How to Cancel Your Subscription.”</p>
    <h2>Future Functionality</h2>
    <p>You agree that your purchases are not contingent on the delivery of any future functionality or features, or dependent on any oral or written public comments made by iByte Apps regarding future functionality or features.</p>
    <h2>Feedback</h2>
    <p>We welcome feedback, comments and suggestions for improvements to the Services or Products (“Feedback”). You can submit Feedback by emailing us at info@12steptoolkit.com. You grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicenseable and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon and otherwise exploit the Feedback for any purpose.</p>
    <h2>Content and Content Rights</h2>
    <p>For purposes of these Terms, (i) “Content” means text, graphics, images, music, software, audio, video, works of authorship of any kind, and information or other materials that are posted, generated, provided or otherwise made available through the Services; and (ii) “User Content” means any Content that users (including you) provide to be made available through the Services. Content includes without limitation User Content.</p>
    <h2>Content Ownership</h2>
    <p>iByte Apps does not claim any ownership rights in any User Content and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit your User Content. Subject to the foregoing, iByte Apps and its licensors exclusively own all right, title and interest in and to the Services and Content, including all associated intellectual property rights. You acknowledge that the Services and Content are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services or Content.</p>
    <p>The Big Book – Alcoholics Anonymous Editions 1 & Editions 2 are public domain material. The name “Alcoholics Anonymous” is in the public domain. iByte Apps is not sponsored by or affiliated to Alcoholics Anonymous, AAWS or any other 12 Step fellowship.</p>
    <h2>Rights in User Content Granted by You</h2>
    <p>By making any User Content available through Services you hereby grant to iByte Apps a non-exclusive, transferable, sublicenseable, worldwide, royalty-free license to use, copy, modify, create derivative works based upon, distribute, publicly display, publicly perform and distribute your User Content in connection with operating and providing the Services and Content to you and to other users.</p>
    <h2>Rights in Content Granted by iByte Apps</h2>
    <p>Subject to your compliance with these Terms, iByte Apps grants you a limited, non-exclusive, non-transferable, non-sublicenseable license to download, view, copy and display the Content solely in connection with your permitted use of the Services and solely for your personal and non-commercial purposes.</p>
    <h2>Rights in App Granted by iByte Apps</h2>
    <p>Subject to your compliance with these Terms, iByte Apps grants you a limited non-exclusive, non-transferable, non-sublicenseable license to download and install a copy of the App on a mobile device or computer that you own or control and to run such copy of the App solely for your own personal non-commercial purposes. iByte Apps reserves all rights in and to the App not expressly granted to you under these Terms. You may not copy the App, except for making a reasonable number of copies for backup or archival purposes. Except as expressly permitted in these Terms, you may not: (i) copy, modify or create derivative works based on the App; (ii) distribute, transfer, sublicense, lease, lend or rent the App to any third party; (iii) reverse engineer, decompile or disassemble the App; or (iv) make the functionality of the App available to multiple users through any means.</p>
    <h2>Additional Terms for App Store Apps</h2>
    <p>If you accessed or downloaded the App from the Apple Store, then you agree to use the App only: (i) on an Apple-branded product or device that runs iOS (Apple’s proprietary operating system software); and (ii) as permitted by the “Usage Rules” set forth in the Apple Store Terms of Service.</p>
    <p>If you accessed or downloaded the App from an App Provider, then you acknowledge and agree that:</p>
    <li>These Terms are concluded between you and iByte Apps, and not with App Provider, and that, as between iByte Apps and the App Provider, iByte Apps, is solely responsible for the App.</li>
    <li>App Provider has no obligation to furnish any maintenance and support services with respect to the App.</li>
    <li>In the event of any failure of the App to conform to any applicable warranty, you may notify App Provider and App Provider will refund the purchase price for the App to you (if applicable) and, to the maximum extent permitted by applicable law, App Provider will have no other warranty obligation whatsoever with respect to the App. Any other claims, losses, liabilities, damages, costs or expenses attributable to any failure of an App to conform to any warranty will be the sole responsibility of iByte Apps.</li>
    <li>App Provider is not responsible for addressing any claims you have or any claims of any third party relating to the App or your possession and use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii)&nbsp;claims arising under consumer protection or similar legislation.</li>
    <li>In the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual property rights, iByte Apps will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms.</li>
    <li>App Provider and its subsidiaries are third-party beneficiaries of these Terms as related to your license of the App, and that, upon your acceptance of the terms and conditions of these Terms, App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the App against you as a third party beneficiary thereof.</li>
    <li>You must also comply with all applicable third-party terms of service when using the App.</li>
    <li>You agree to comply with all U.S. and foreign export laws and regulations to ensure that neither the App nor any technical data related thereto nor any direct product thereof is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations. By using the App you represent and warrant that: (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</li>
    <h2>Prohibitions</h2>
    <p>You agree not to do any of the following:</p>
    <li>Post, upload, publish, submit or transmit any Content that: (i)&nbsp;infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v)&nbsp;promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii)&nbsp;promotes illegal or harmful activities or substances;</li>
    <li>Use, display, mirror or frame the Services, or any individual element within the Services, iByte Apps’ name, any iByte Apps trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without iByte Apps’s express written consent;</li>
    <li>Access, tamper with, or use non-public areas of the Services, iByte Apps’s computer systems, or the technical delivery systems of iByte Apps’s providers;</li>
    <li>Attempt to probe, scan, or test the vulnerability of any iByte Apps system or network or breach any security or authentication measures;</li>
    <li>Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by iByte Apps or any of iByte Apps’s providers or any other third party (including another user) to protect the Services;</li>
    <li>Attempt to access or search the Services or download Collective Content from the Services through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by iByte Apps or other generally available third party web browsers;</li>
    <li>Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;</li>
    <li>Use any meta tags or other hidden text or metadata utilizing a iByte Apps trademark, logo URL or product name without iByte Apps’s express written consent;</li>
    <li>Use the Services for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms;</li>
    <li>Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services to send altered, deceptive or false source-identifying information;</li>
    <li>Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services;</li>
    <li>Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services;</li>
    <li>Collect or store any personally identifiable information from the Services from other users of the Services without their express permission;</li>
    <li>Impersonate or misrepresent your affiliation with any person or entity;</li>
    <li>Violate any applicable law or regulation; or</li>
    <li>Encourage or enable any other individual to do any of the foregoing.</li>
    <h2>Our Monitoring Rights</h2>
    <p>Although we’re not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>
    <h2>Links to Third Party Websites or Resources</h2>
    <p>The Services and App may contain links to third-party websites or resources. We provide these links only as a convenience and are not responsible for the content, products or services on or available from those websites or resources or links displayed on such websites. You acknowledge sole responsibility for and assume all risk arising from, your use of any third-party websites or resources.</p>
    <h2>Termination</h2>
    <p>We may terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. You may cancel your Account at any time by sending an email to us at info@12steptoolkit.com. If you purchase Subscription via an App Provider, you should also cancel your Subscription with the App Provider directly. Upon any termination, discontinuation or cancellation of Services or your Account, all provisions of these Terms which by their nature should survive will survive, including, without limitation, ownership provisions, warranty disclaimers, limitations of liability, and dispute resolution provisions.</p>
    <h2>Warranty Disclaimers</h2>
    <p>The Services, Products and Content are provided “as is,” without warranty of any kind. Without limiting the foregoing, we explicitly disclaim any warranties of merchantability, fitness for a particular purpose, quiet enjoyment or non-infringement and any warranties arising out of course of dealing or usage of trade.</p>
    <p>We make no warranty that the Services or Products will meet your requirements or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness or reliability of any Content.</p>
    <h2>Indemnity</h2>
    <p>You will indemnify and hold harmless iByte Apps and its officers, directors, employee and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (i) your access to or use of the Services or Content or (ii) your violation of these Terms.</p>
    <h2>Limitation of Liability</h2>
    <p>Neither iByte Apps nor any other party involved in creating, producing, or delivering the Services, Products or Content will be liable for any incidental, special, exemplary or consequential damages, including, but not limited to, lost profits, loss of data or goodwill, service interruption, computer damage or system failure or the cost of substitute Services or Products arising out of or in connection with these terms or from the use of or inability to use the Services, Products or Content, whether based on warranty, contract, tort (including negligence), product liability or any other legal theory, and whether or not iByte Apps has been informed of the possibility of such damage, even if a limited remedy set forth herein is found to have failed of its essential purpose. Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, so the above limitation may not apply to you.</p>
    <p>In no event will iByte Apps’ total liability arising out of or in connection with these terms or from the use of or inability to use the Services, Products or Content exceed the amounts you have paid to iByte Apps for use of the Services, Products or Content or fifty dollars ($40), if you have not had any payment obligations to iByte Apps, as applicable. The exclusion and limitations of damages set forth above are fundamental elements of the basis of the bargain between iByte Apps and you.</p>
    <h2>Dispute Resolution - Governing Law</h2>
    <p>These Terms and any action related thereto will be governed by the laws of the England & Wales without regard to its conflict of laws provisions.</p>
    <h2>Dispute Resolution - Agreement to Mediation</h2>
    <p>You and iByte Apps agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services, Products or Content (collectively, “Disputes”) will be settled by binding mediation, except that each party retains the right: (i) to bring an individual action in small claims court and (ii) to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights (the action described in the foregoing clause (ii), an “IP Protection Action”). Without limiting the preceding sentence, you will also have the right to litigate any other Dispute if you provide iByte Apps with written notice of your desire to do so by email at info@12steptoolkit.com within thirty (30) days following the date you first agree to these Terms (such notice, an “Mediation Opt-out Notice”). If you don’t provide iByte Apps with an Mediation Opt-out Notice within the thirty (30) day period, you will be deemed to have knowingly and intentionally waived your right to litigate any Dispute except as expressly set forth in clauses (i) and (ii) above. The exclusive jurisdiction and venue of any IP Protection Action or, if you timely provide iByte Apps with an Mediation Opt-out Notice, will be the courts located in England & Wales and each of the parties hereto waives any objection to jurisdiction and venue in such courts. Unless you timely provide iByte Apps with an Mediation Opt-out Notice, you acknowledge and agree that you and iByte Apps are each waiving the right to a trial by jury or to participate as a claimant or class member in any purported class action or representative proceeding. Further, unless both you and iByte Apps otherwise agree in writing, the mediator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.</p>
    <h2>Dispute Resolution - Mediation Rules</h2>
    <p>The mediation will be administered by the Intellectual Property Office (IPO) or another relevant office if the case is not in connection with intellectual property, in accordance with the laws in England & Wales. Unless you and iByte Apps otherwise agree, the mediation will be conducted in the Northamptonshire.</p>
    <h2>Dispute Resolution - Changes</h2>
    <p>Notwithstanding the provisions of the “Modification” section above, if iByte Apps changes this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to info@12steptoolkit.com) within 30 days of the date such change became effective, as indicated in the “Last Updated” date above or in the date of iByte Apps’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will mediate any Dispute between you and iByte Apps in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
    <h2>General Terms</h2>
    <p>These Terms constitute the entire and exclusive understanding and agreement between iByte Apps and you regarding the Services, Products and Content, and these Terms supersede and replace any and all prior oral or written understandings or agreements between iByte Apps and you regarding the Services, Products and Content. If any provision of these Terms is held invalid or unenforceable (either by an mediator appointed pursuant to the terms of the “Mediation” section above or by court of competent jurisdiction, but only if you timely opt out of mediation by sending us an Mediation Opt-out Notice in accordance with the terms set forth above), that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
    <p>You may not assign or transfer these Terms, by operation of law or otherwise, without iByte Apps’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. iByte Apps may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
    <p>Any notices or other communications provided by iByte Apps under these Terms, including those regarding modifications to these Terms, will be given: (i) by iByte Apps via email; or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
    <p>iByte Apps’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of iByte Apps. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</p>
    <h2>Contact Information</h2>
    <p>If you have any questions about these Terms or the Services or Products, please contact iByte Apps at info@12steptoolkit.com.</p>
    </article>
</x-site-layout>
