<?php

/*
|--------------------------------------------------------------------------
| The A.A. literature index
|--------------------------------------------------------------------------
|
| 105 pages: 17 Big Book sections, 29 personal stories from the first
| edition, 40 from the second, 11 prayers and 8 readings. Each one is a
| slug, the HTML file holding it under `resources/site/literature/`, and
| the metadata search engines already have for it.
|
| ## Converted, not retyped
|
| This file was generated from the three registries the Next.js site used
| — `data/literatureRegistry.js`, `prayerRegistry.js`, `readingsRegistry.js`
| — by letting Node evaluate them and dumping the result. Every title,
| description and keyword list is therefore byte-for-byte what Google has
| indexed, including the curly apostrophes. Retyping 105 entries by hand
| would have been a slow way to lose a few of them.
|
| ## The slug is the URL
|
| A slug with no slash is a Big Book section and lives under
| `/aa-literature/big-book/<slug>`. A slug with one is already its own
| path: `prayers/serenity-prayer` is `/aa-literature/prayers/serenity-prayer`.
| `App\Services\Site\LiteratureLibrary::pathFor()` is the single place
| that rule is written down.
|
| `order` and `menuLabel` exist only on the Big Book sections, which are the
| ones with a reading order; the stories, prayers and readings are listed
| in the order they appear here.
*/

return [
    'preface' => [
        'fileName' => 'preface.html',
        'title' => 'Preface to the Fourth Edition | AA Big Book | 12 Step Toolkit',
        'desc' => 'Read the Preface to the Fourth Edition of Alcoholics Anonymous. Learn about the history and growth of the AA fellowship.',
        'keywords' => 'AA Big Book Preface, Alcoholics Anonymous history, 4th edition preface',
        'group' => 'Introductory',
        'order' => 1,
        'menuLabel' => 'Preface (4th Edition)',
    ],
    'foreword-first-edition' => [
        'fileName' => 'foreword-first-edition.html',
        'title' => 'Foreword to the First Edition | Original 1939 AA Text',
        'desc' => 'The original 1939 foreword to Alcoholics Anonymous. Understanding the core purpose of the recovery program.',
        'keywords' => 'AA 1939 foreword, recovery purpose, original AA text',
        'group' => 'Introductory',
        'order' => 2,
        'menuLabel' => 'Foreword (1st Edition)',
    ],
    'foreword-second-edition' => [
        'fileName' => 'foreword-second-edition.html',
        'title' => 'Foreword to the Second Edition | Growth of AA',
        'desc' => 'Explore the Foreword to the Second Edition, detailing how Alcoholics Anonymous grew from a small group to a global movement.',
        'keywords' => 'AA second edition, growth of AA, 12 traditions history',
        'group' => 'Introductory',
        'order' => 3,
        'menuLabel' => 'Foreword (2nd Edition)',
    ],
    'doctors-opinion' => [
        'fileName' => 'doctors-opinion.html',
        'title' => 'The Doctor\'s Opinion - Dr. Silkworth | AA Big Book',
        'desc' => 'Dr. William Silkworth\'s medical perspective on alcoholism as an allergy of the body and an obsession of the mind.',
        'keywords' => 'Dr Silkworth, allergy of alcoholism, medical opinion AA, the doctor\'s opinion',
        'group' => 'Introductory',
        'order' => 4,
        'menuLabel' => 'The Doctor’s Opinion',
    ],
    'bills-story' => [
        'fileName' => 'bills-story.html',
        'title' => 'Bill\'s Story - Chapter 1 | AA Big Book | Tape 2',
        'desc' => 'Chapter 1 of the Big Book: Bill Wilson\'s journey from hopeless alcoholism to founding Alcoholics Anonymous.',
        'keywords' => 'Bill\'s Story, Chapter 1 Big Book, Bill Wilson, AA Tape 2',
        'group' => 'Chapters',
        'order' => 5,
        'menuLabel' => 'Bill’s Story (Ch. 1)',
    ],
    'there-is-a-solution' => [
        'fileName' => 'there-is-a-solution.html',
        'title' => 'There is a Solution - Chapter 2 | AA Big Book | Tape 3',
        'desc' => 'Chapter 2 explains the fellowship and the common solution that allows alcoholics to recover together.',
        'keywords' => 'There is a solution, AA Chapter 2, fellowship of recovery, AA Tape 3',
        'group' => 'Chapters',
        'order' => 6,
        'menuLabel' => 'There Is a Solution (Ch. 2)',
    ],
    'more-about-alcoholism' => [
        'fileName' => 'tape4.html',
        'title' => 'More About Alcoholism - Chapter 3 | AA Big Book | Tape 4',
        'desc' => 'Chapter 3 discusses the \'illusion\' that the alcoholic can one day drink like other people and why it must be smashed.',
        'keywords' => 'More about alcoholism, Chapter 3 Big Book, alcoholic illusion, AA Tape 4',
        'group' => 'Chapters',
        'order' => 7,
        'menuLabel' => 'More About Alcoholism (Ch. 3)',
    ],
    'we-agnostics' => [
        'fileName' => 'tape5.html',
        'title' => 'We Agnostics - Chapter 4 | AA Big Book | Tape 5',
        'desc' => 'A chapter for those who struggle with the concept of God or a Higher Power. Find a path to spiritual recovery.',
        'keywords' => 'We Agnostics, AA Chapter 4, higher power for atheists, spiritual path, AA Tape 5',
        'group' => 'Chapters',
        'order' => 8,
        'menuLabel' => 'We Agnostics (Ch. 4)',
    ],
    'how-it-works' => [
        'fileName' => 'tape6.html',
        'title' => 'How It Works - Chapter 5 | The 12 Steps | Tape 6',
        'desc' => 'The core of the program. Read the Twelve Steps of Alcoholics Anonymous as outlined in Chapter 5.',
        'keywords' => 'How it works, AA 12 steps, Chapter 5 Big Book, AA Tape 6',
        'group' => 'Chapters',
        'order' => 9,
        'menuLabel' => 'How It Works (Ch. 5)',
    ],
    'into-action' => [
        'fileName' => 'tape7.html',
        'title' => 'Into Action - Chapter 6 | Steps 5 through 11 | Tape 7',
        'desc' => 'Practical directions for taking Steps 5, 6, 7, 8, 9, 10, and 11 to maintain a spiritual experience.',
        'keywords' => 'Into action, AA Chapter 6, making amends, daily inventory, AA Tape 7',
        'group' => 'Chapters',
        'order' => 10,
        'menuLabel' => 'Into Action (Ch. 6)',
    ],
    'working-with-others' => [
        'fileName' => 'tape8.html',
        'title' => 'Working With Others - Chapter 7 | Step 12 | Tape 8',
        'desc' => 'The vital importance of carrying the message to other alcoholics. Step 12 in practice.',
        'keywords' => 'Working with others, Step 12, AA Chapter 7, sponsorship, AA Tape 8',
        'group' => 'Chapters',
        'order' => 11,
        'menuLabel' => 'Working With Others (Ch. 7)',
    ],
    'to-wives' => [
        'fileName' => 'tape9.html',
        'title' => 'To Wives - Chapter 8 | Family Recovery | Tape 9',
        'desc' => 'Guidance for the partners and spouses of alcoholics to find their own recovery and understanding.',
        'keywords' => 'To wives, AA Chapter 8, family recovery, living with an alcoholic, AA Tape 9',
        'group' => 'Chapters',
        'order' => 12,
        'menuLabel' => 'To Wives (Ch. 8)',
    ],
    'the-family-afterward' => [
        'fileName' => 'tape10.html',
        'title' => 'The Family Afterward - Chapter 9 | AA Big Book | Tape 10',
        'desc' => 'Healing the family dynamic and rebuilding relationships after the alcoholic stops drinking.',
        'keywords' => 'The family afterward, Chapter 9 Big Book, family healing, AA Tape 10',
        'group' => 'Chapters',
        'order' => 13,
        'menuLabel' => 'The Family Afterward (Ch. 9)',
    ],
    'to-employers' => [
        'fileName' => 'tape11.html',
        'title' => 'To Employers - Chapter 10 | Alcoholism in the Workplace | Tape 11',
        'desc' => 'Advice for business owners and managers on how to handle and help alcoholic employees.',
        'keywords' => 'To employers, AA Chapter 10, workplace alcoholism, AA Tape 11',
        'group' => 'Chapters',
        'order' => 14,
        'menuLabel' => 'To Employers (Ch. 10)',
    ],
    'a-vision-for-you' => [
        'fileName' => 'tape12.html',
        'title' => 'A Vision For You - Chapter 11 | AA Fellowship | Tape 12',
        'desc' => 'The concluding chapter of the main text, offering a vision of the fellowship and future for the recovered alcoholic.',
        'keywords' => 'A vision for you, AA Chapter 11, fellowship of the spirit, AA Tape 12',
        'group' => 'Chapters',
        'order' => 15,
        'menuLabel' => 'A Vision For You (Ch. 11)',
    ],
    'dr-bobs-nightmare' => [
        'fileName' => 'tape13.html',
        'title' => 'Dr. Bob\'s Nightmare | Story of the AA Co-Founder | Tape 13',
        'desc' => 'The personal history of Dr. Bob Smith, the Akron physician who co-founded Alcoholics Anonymous.',
        'keywords' => 'Dr Bob Smith, co-founder of AA, Dr Bob\'s Nightmare, AA Tape 13',
        'group' => 'Personal Stories',
        'order' => 16,
        'menuLabel' => 'Dr. Bob’s Nightmare',
    ],
    'aa-number-three' => [
        'fileName' => 'tape14.html',
        'title' => 'He Sold Himself Short (AA Number 3) | Big Book Story | Tape 14',
        'desc' => 'The story of the third man to get sober in AA, Bill D., whose recovery proved that the program worked.',
        'keywords' => 'AA number 3, He sold himself short, Bill D AA, AA Tape 14',
        'group' => 'Personal Stories',
        'order' => 17,
        'menuLabel' => 'AA Number Three',
    ],
    'stories-edition-1/the-doctors-nightmare' => [
        'fileName' => 'stories1/stories1_1.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Doctor’s Nightmare'],
        'title' => 'The Doctor’s Nightmare | 1st Edition Personal Stories | AA',
        'desc' => 'The story of Dr. Bob, the co-founder of Alcoholics Anonymous.',
        'keywords' => 'Dr. Bob, Doctor\'s Nightmare, AA co-founder, pioneer story',
    ],
    'stories-edition-1/the-unbeliever' => [
        'fileName' => 'stories1/stories1_2.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Unbeliever'],
        'title' => 'The Unbeliever | 1st Edition Personal Stories | AA',
        'desc' => 'A pioneer story of finding faith and recovery in early AA.',
        'keywords' => 'AA stories edition 1, pioneer stories, the unbeliever',
    ],
    'stories-edition-1/the-european-drinker' => [
        'fileName' => 'stories1/stories1_3.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The European Drinker'],
        'title' => 'The European Drinker | 1st Edition Personal Stories | AA',
        'desc' => 'Personal recovery account from the original 1939 AA text.',
        'keywords' => 'European drinker, AA 1st edition stories',
    ],
    'stories-edition-1/a-feminine-victory' => [
        'fileName' => 'stories1/stories1_4.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'A Feminine Victory'],
        'title' => 'A Feminine Victory | 1st Edition Personal Stories | AA',
        'desc' => 'A pioneer story of a woman\'s journey to sobriety in the early days of Alcoholics Anonymous.',
        'keywords' => 'AA women stories, feminine victory, pioneer recovery',
    ],
    'stories-edition-1/our-southern-friend' => [
        'fileName' => 'stories1/stories1_5.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Our Southern Friend'],
        'title' => 'Our Southern Friend | AA 1st Edition Personal Stories',
        'desc' => 'The story of a Southern gentleman\'s struggle and eventual spiritual awakening.',
        'keywords' => 'Our southern friend, AA history, spiritual awakening',
    ],
    'stories-edition-1/a-business-mans-recovery' => [
        'fileName' => 'stories1/stories1_6.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'A Business Man\'s Recovery'],
        'title' => 'A Business Man\'s Recovery | AA Big Book Personal Stories',
        'desc' => 'How a successful professional reclaimed his life from chronic alcoholism.',
        'keywords' => 'business man recovery, executive sobriety, AA pioneer',
    ],
    'stories-edition-1/a-different-slant' => [
        'fileName' => 'stories1/stories1_7.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'A Different Slant'],
        'title' => 'A Different Slant | 1st Edition Personal Stories | AA',
        'desc' => 'A short but powerful account of a unique perspective on the AA program.',
        'keywords' => 'A different slant, AA short stories, first edition',
    ],
    'stories-edition-1/traveler-editor-scholar' => [
        'fileName' => 'stories1/stories1_8.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Traveler, Editor, Scholar'],
        'title' => 'Traveler, Editor, Scholar | 1st Edition Personal Stories | AA',
        'desc' => 'The journey of an intellectual and world traveler finding sobriety.',
        'keywords' => 'traveler editor scholar, intellectual alcoholic, AA history',
    ],
    'stories-edition-1/the-back-slider' => [
        'fileName' => 'stories1/stories1_9.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Back-Slider'],
        'title' => 'The Back-Slider | Dealing with Relapse in Early AA',
        'desc' => 'An honest look at the struggle of backsliding and finding the strength to return.',
        'keywords' => 'the backslider, relapse, AA persistence',
    ],
    'stories-edition-1/home-brewmeister' => [
        'fileName' => 'stories1/stories1_10.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Home Brewmeister'],
        'title' => 'Home Brewmeister | 1st Edition AA Personal Stories',
        'desc' => 'The story of a man whose drinking escalated during the era of home-made beer.',
        'keywords' => 'home brewmeister, prohibition era, AA stories',
    ],
    'stories-edition-1/the-seventh-month-slip' => [
        'fileName' => 'stories1/stories1_11.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Seventh Month Slip'],
        'title' => 'The Seventh Month Slip | 1st Edition Personal Stories | AA',
        'desc' => 'An account of early sobriety and the lessons learned from a slip.',
        'keywords' => 'seventh month slip, AA relapse, pioneer recovery',
    ],
    'stories-edition-1/my-wife-and-i' => [
        'fileName' => 'stories1/stories1_12.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'My Wife and I'],
        'title' => 'My Wife and I | 1st Edition AA Personal Stories',
        'desc' => 'A story highlighting the impact of alcoholism on marriage and the power of joint recovery.',
        'keywords' => 'my wife and i, AA marriage, family recovery',
    ],
    'stories-edition-1/a-ward-of-the-probate-court' => [
        'fileName' => 'stories1/stories1_13.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'A Ward of the Probate Court'],
        'title' => 'A Ward of the Probate Court | 1st Edition AA Stories',
        'desc' => 'A journey from legal consequences to spiritual freedom.',
        'keywords' => 'probate court, legal issues, AA pioneer stories',
    ],
    'stories-edition-1/riding-the-rods' => [
        'fileName' => 'stories1/stories1_14.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Riding the Rods'],
        'title' => 'Riding the Rods | 1st Edition Personal Stories | AA',
        'desc' => 'The story of a wandering alcoholic finding a home in the fellowship.',
        'keywords' => 'riding the rods, transient drinking, AA history',
    ],
    'stories-edition-1/the-salesman' => [
        'fileName' => 'stories1/stories1_15.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Salesman'],
        'title' => 'The Salesman | AA Big Book 1st Edition Stories',
        'desc' => 'A classic account of a salesman\'s journey from the road to the rooms of AA.',
        'keywords' => 'the salesman, AA road, career and sobriety',
    ],
    'stories-edition-1/fired-again' => [
        'fileName' => 'stories1/stories1_16.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Fired Again'],
        'title' => 'Fired Again | Unemployment and Alcoholism | AA Story',
        'desc' => 'Addressing the cycle of losing jobs due to drinking.',
        'keywords' => 'fired again, job loss, AA work life',
    ],
    'stories-edition-1/the-fearful-one' => [
        'fileName' => 'stories1/stories1_17.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Fearful One'],
        'title' => 'The Fearful One | Overcoming Fear in AA | 1st Ed',
        'desc' => 'Addressing the deep-seated fears that drive alcoholism.',
        'keywords' => 'overcoming fear, AA spirituality, fearful one',
    ],
    'stories-edition-1/truth-freed-me' => [
        'fileName' => 'stories1/stories1_18.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Truth Freed Me!'],
        'title' => 'Truth Freed Me! | 1st Edition Personal Stories | AA',
        'desc' => 'How honesty and truth became the foundation for a new life.',
        'keywords' => 'truth freed me, honesty, AA recovery',
    ],
    'stories-edition-1/smile-with-me-at-me' => [
        'fileName' => 'stories1/stories1_19.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Smile with Me, At Me'],
        'title' => 'Smile with Me, At Me | 1st Edition AA Stories',
        'desc' => 'A story about learning to not take oneself too seriously in recovery.',
        'keywords' => 'smile with me, humility, AA humor',
    ],
    'stories-edition-1/a-close-shave' => [
        'fileName' => 'stories1/stories1_20.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'A Close Shave'],
        'title' => 'A Close Shave | 1st Edition Personal Stories | AA',
        'desc' => 'A harrowing story of near misses and final recovery.',
        'keywords' => 'a close shave, AA miracle, pioneer story',
    ],
    'stories-edition-1/educated-agnostic' => [
        'fileName' => 'stories1/stories1_21.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Educated Agnostic'],
        'title' => 'Educated Agnostic | Intellectual Barriers to AA',
        'desc' => 'How intellectual pride and agnosticism were overcome.',
        'keywords' => 'educated agnostic, intellectualism, AA spiritual',
    ],
    'stories-edition-1/another-prodigal-story' => [
        'fileName' => 'stories1/stories1_22.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Another Prodigal Story'],
        'title' => 'Another Prodigal Story | 1st Edition AA Personal Stories',
        'desc' => 'A moving account of returning to a life of sanity.',
        'keywords' => 'prodigal son, AA return, recovery journey',
    ],
    'stories-edition-1/the-car-smasher' => [
        'fileName' => 'stories1/stories1_23.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Car Smasher'],
        'title' => 'The Car Smasher | Pioneer Stories AA Big Book',
        'desc' => 'The story of an alcoholic whose path of destruction ended in AA.',
        'keywords' => 'car smasher, AA miracle, pioneer story',
    ],
    'stories-edition-1/hindsight' => [
        'fileName' => 'stories1/stories1_24.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Hindsight'],
        'title' => 'Hindsight | Reflections on Recovery | AA Big Book',
        'desc' => 'Looking back at a life of drinking from a recovered perspective.',
        'keywords' => 'hindsight, AA reflection, life before AA',
    ],
    'stories-edition-1/on-his-way' => [
        'fileName' => 'stories1/stories1_25.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'On His Way'],
        'title' => 'On His Way | 1st Edition AA Personal Stories',
        'desc' => 'A story of progress and the ongoing journey of the AA way of life.',
        'keywords' => 'on his way, AA progress, daily reprieve',
    ],
    'stories-edition-1/an-alcoholics-wife' => [
        'fileName' => 'stories1/stories1_26.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'An Alcoholic’s Wife'],
        'title' => 'An Alcoholic’s Wife | 1st Edition Personal Stories | AA',
        'desc' => 'The unique perspective of a spouse in the early AA community.',
        'keywords' => 'alcoholic\'s wife, Al-Anon roots, AA family',
    ],
    'stories-edition-1/an-artists-concept' => [
        'fileName' => 'stories1/stories1_27.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'An Artist\'s Concept'],
        'title' => 'An Artist\'s Concept | Spirituality and Creativity in AA',
        'desc' => 'How an artist found a power greater than himself.',
        'keywords' => 'artist concept, creativity, AA higher power',
    ],
    'stories-edition-1/the-rolling-stone' => [
        'fileName' => 'stories1/stories1_28.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'The Rolling Stone'],
        'title' => 'The Rolling Stone | 1st Edition AA Personal Stories',
        'desc' => 'The story of a man who traveled far but couldn\'t outrun his drinking.',
        'keywords' => 'rolling stone, geographic cure, AA recovery',
    ],
    'stories-edition-1/now-we-are-thousands' => [
        'fileName' => 'stories1/stories1_29.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 1', 'Now We Are Thousands'],
        'title' => 'Now We Are Thousands | 1st Edition Personal Stories | AA',
        'desc' => 'The concluding story of the first edition, reflecting on the growth of the movement.',
        'keywords' => 'now we are thousands, AA growth, fellowship',
    ],
    'stories-edition-2/pioneers-of-aa' => [
        'fileName' => 'stories2/stories2_1.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Pioneers of A.A.'],
        'title' => 'Pioneers of A.A. | 2nd Edition Personal Stories | AA',
        'desc' => 'An introduction to the early members who formed the first A.A. groups.',
        'keywords' => 'Pioneers of AA, early members, Akron group 1',
    ],
    'stories-edition-2/doctor-bobs-nightmare' => [
        'fileName' => 'stories2/stories2_2.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Doctor Bob\'s Nightmare'],
        'title' => 'Doctor Bob\'s Nightmare | AA Co-Founder\'s Story',
        'desc' => 'The foundational story of Dr. Bob and the birth of Alcoholics Anonymous on June 10, 1935.',
        'keywords' => 'Dr Bob, AA co-founder, Doctor Bob\'s Nightmare',
    ],
    'stories-edition-2/alcoholic-anonymous-number-three' => [
        'fileName' => 'stories2/stories2_3.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Alcoholic Anonymous Number Three'],
        'title' => 'Alcoholic Anonymous Number Three | Bill D. Story',
        'desc' => 'The story of the man who was the third member of A.A. and kept the faith in Akron.',
        'keywords' => 'AA number 3, Bill D, Akron Group 1',
    ],
    'stories-edition-2/he-had-to-be-shown' => [
        'fileName' => 'stories2/stories2_4.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'He Had To Be Shown'],
        'title' => 'He Had To Be Shown | 2nd Edition Personal Stories | AA',
        'desc' => 'The story of an oldest member who was convinced of the program\'s power against his will.',
        'keywords' => 'He had to be shown, AA history, pioneer stories',
    ],
    'stories-edition-2/he-thought-he-could-drink-like-a-gentleman' => [
        'fileName' => 'stories2/stories2_5.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'He Thought He Could Drink Like A Gentleman'],
        'title' => 'He Thought He Could Drink Like A Gentleman | AA Stories',
        'desc' => 'A Cleveland pioneer\'s account of trying to control his drinking.',
        'keywords' => 'drink like a gentleman, Cleveland AA, pioneer member',
    ],
    'stories-edition-2/women-suffer-too' => [
        'fileName' => 'stories2/stories2_6.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Women Suffer Too'],
        'title' => 'Women Suffer Too | Early Women in AA | 2nd Edition',
        'desc' => 'Marty M.\'s story of being one of the first women to find sobriety in A.A.',
        'keywords' => 'Women suffer too, Marty Mann, women in AA',
    ],
    'stories-edition-2/the-european-drinker' => [
        'fileName' => 'stories2/stories2_7.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The European Drinker'],
        'title' => 'The European Drinker | 2nd Edition Personal Stories | AA',
        'desc' => ' Alsace-born member finds that beer and wine were not the answer to his problem.',
        'keywords' => 'European drinker, Alsace, AA stories',
    ],
    'stories-edition-2/the-vicious-cycle' => [
        'fileName' => 'stories2/stories2_8.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Vicious Cycle'],
        'title' => 'The Vicious Cycle | Starting AA in Philadelphia',
        'desc' => 'How a salesman broke his obstinacy and helped start A.A. in Philadelphia.',
        'keywords' => 'vicious cycle, Philadelphia AA, Jim B',
    ],
    'stories-edition-2/the-news-hawk' => [
        'fileName' => 'stories2/stories2_9.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The News Hawk'],
        'title' => 'The News Hawk | 2nd Edition Personal Stories | AA',
        'desc' => 'A newsman\'s journey through life\'s highs and lows to find safety in A.A.',
        'keywords' => 'news hawk, journalist recovery, AA stories',
    ],
    'stories-edition-2/from-farm-to-city' => [
        'fileName' => 'stories2/stories2_10.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'From Farm To City'],
        'title' => 'From Farm To City | Pioneer Woman Member | AA',
        'desc' => 'A pioneer woman from the first group shares how A.A. works during rough times.',
        'keywords' => 'farm to city, pioneer woman, AA group 1',
    ],
    'stories-edition-2/the-man-who-mastered-fear' => [
        'fileName' => 'stories2/stories2_11.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Man Who Mastered Fear'],
        'title' => 'The Man Who Mastered Fear | Starting AA in Detroit',
        'desc' => 'He spent 18 years running away before finding he didn\'t have to; started A.A. in Detroit.',
        'keywords' => 'mastering fear, Detroit AA, pioneer member',
    ],
    'stories-edition-2/he-sold-himself-short' => [
        'fileName' => 'stories2/stories2_12.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'He Sold Himself Short'],
        'title' => 'He Sold Himself Short | 2nd Edition AA Stories',
        'desc' => 'Finding a Higher Power that had more faith in him than he had in himself.',
        'keywords' => 'sold himself short, higher power, AA success',
    ],
    'stories-edition-2/home-brewmeister' => [
        'fileName' => 'stories2/stories2_13.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Home Brewmeister'],
        'title' => 'Home Brewmeister | Cleveland Group No. 3 | AA',
        'desc' => 'A story of fighting Prohibition and becoming a founder of Cleveland\'s third group.',
        'keywords' => 'home brewmeister, Cleveland AA, prohibition',
    ],
    'stories-edition-2/the-keys-of-the-kingdom' => [
        'fileName' => 'stories2/stories2_14.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Keys Of The Kingdom'],
        'title' => 'The Keys Of The Kingdom | Chicago AA History',
        'desc' => 'A worldly lady who helped develop A.A. in Chicago and passed her keys to many.',
        'keywords' => 'keys of the kingdom, Chicago AA, Sylvia K',
    ],
    'stories-edition-2/they-stopped-in-time' => [
        'fileName' => 'stories2/stories2_15.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'They Stopped In Time'],
        'title' => 'They Stopped In Time | High-Bottom AA Stories',
        'desc' => 'Introduction to stories of members who were not yet \'advanced cases\'.',
        'keywords' => 'stopped in time, high bottom, AA growth',
    ],
    'stories-edition-2/rum-radio-and-rebellion' => [
        'fileName' => 'stories2/stories2_16.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Rum, Radio And Rebellion'],
        'title' => 'Rum, Radio And Rebellion | 2nd Edition AA Stories',
        'desc' => 'A man facing his \'last-ditch\' finds A.A. through his wife\'s voice.',
        'keywords' => 'rum radio rebellion, AA stories, high bottom',
    ],
    'stories-edition-2/fear-of-fear' => [
        'fileName' => 'stories2/stories2_17.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Fear Of Fear'],
        'title' => 'Fear Of Fear | High-Bottom Woman\'s Story | AA',
        'desc' => 'A lady who tried to be cautious with her drinking but found her life becoming unmanageable.',
        'keywords' => 'fear of fear, lady alcoholic, cautious drinking',
    ],
    'stories-edition-2/the-professor-and-the-paradox' => [
        'fileName' => 'stories2/stories2_18.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Professor And The Paradox'],
        'title' => 'The Professor And The Paradox | AA Philosophy',
        'desc' => 'Exploring the spiritual paradoxes of the A.A. program: surrender to win.',
        'keywords' => 'professor and paradox, surrender to win, AA philosophy',
    ],
    'stories-edition-2/a-flower-of-the-south' => [
        'fileName' => 'stories2/stories2_19.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'A Flower Of The South'],
        'title' => 'A Flower Of The South | 2nd Edition Personal Stories',
        'desc' => 'A story of blooming afresh and helping start A.A. in the deep South.',
        'keywords' => 'flower of the south, Southern AA, recovery',
    ],
    'stories-edition-2/unto-the-second-generation' => [
        'fileName' => 'stories2/stories2_20.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Unto The Second Generation'],
        'title' => 'Unto The Second Generation | Young Veterans in AA',
        'desc' => 'A young veteran tells how early intervention in A.A. spared him years of suffering.',
        'keywords' => 'second generation, young people in AA, veteran recovery',
    ],
    'stories-edition-2/his-conscience' => [
        'fileName' => 'stories2/stories2_21.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'His Conscience'],
        'title' => 'His Conscience | 2nd Edition Personal Stories | AA',
        'desc' => 'The realization that his conscience was the only part of him soluble to alcohol.',
        'keywords' => 'his conscience, moral inventory, AA stories',
    ],
    'stories-edition-2/the-housewife-who-drank-at-home' => [
        'fileName' => 'stories2/stories2_22.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Housewife Who Drank At Home'],
        'title' => 'The Housewife Who Drank At Home | Secret Drinking',
        'desc' => 'The story of hidden bottles and the realization of what she was becoming.',
        'keywords' => 'housewife, home drinker, hidden bottles',
    ],
    'stories-edition-2/it-might-have-been-worse' => [
        'fileName' => 'stories2/stories2_23.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'It Might Have Been Worse'],
        'title' => 'It Might Have Been Worse | Banker\'s Recovery Story',
        'desc' => 'A banker uses rare foresight to join A.A. before his \'cloud\' became a \'tornado\'.',
        'keywords' => 'might have been worse, banker, foresight',
    ],
    'stories-edition-2/physician-heal-thyself' => [
        'fileName' => 'stories2/stories2_24.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Physician, Heal Thyself!'],
        'title' => 'Physician, Heal Thyself! | Doctors in AA',
        'desc' => 'A psychiatrist and surgeon realizes that God is the Great Healer.',
        'keywords' => 'physician heal thyself, doctor in AA, psychiatrist recovery',
    ],
    'stories-edition-2/stars-dont-fall' => [
        'fileName' => 'stories2/stories2_25.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Stars Don’t Fall'],
        'title' => 'Stars Don’t Fall | 2nd Edition Personal Stories | AA',
        'desc' => 'A titled lady regains her self-respect after the overcast of alcohol lifts.',
        'keywords' => 'stars dont fall, self-respect, titled lady',
    ],
    'stories-edition-2/me-an-alcoholic' => [
        'fileName' => 'stories2/stories2_26.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Me An Alcoholic?'],
        'title' => 'Me An Alcoholic? | An Author\'s Recovery | AA',
        'desc' => 'An author\'s account of being squeezed by the \'Barleycorn wringer\' and escaping.',
        'keywords' => 'me an alcoholic, author story, recovery',
    ],
    'stories-edition-2/new-vision-for-a-sculptor' => [
        'fileName' => 'stories2/stories2_27.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'New Vision For A Sculptor'],
        'title' => 'New Vision For A Sculptor | 2nd Edition AA Stories',
        'desc' => 'A sculptor finds relief from a hurting conscience and a drinking problem.',
        'keywords' => 'new vision, sculptor, conscience',
    ],
    'stories-edition-2/they-lost-nearly-all' => [
        'fileName' => 'stories2/stories2_28.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'They Lost Nearly All'],
        'title' => 'They Lost Nearly All | Low-Bottom AA Stories',
        'desc' => 'Stories of alcoholics at their miserable worst who found hope in A.A.',
        'keywords' => 'lost nearly all, low bottom, rock bottom stories',
    ],
    'stories-edition-2/joes-woes' => [
        'fileName' => 'stories2/stories2_29.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Joe’s Woes'],
        'title' => 'Joe’s Woes | Bellevue and Beyond | AA Stories',
        'desc' => 'After 35 times in Bellevue, Joe finally finds a way out through A.A.',
        'keywords' => 'joes woes, Bellevue hospital, chronic alcoholic',
    ],
    'stories-edition-2/our-southern-friend' => [
        'fileName' => 'stories2/stories2_30.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Our Southern Friend'],
        'title' => 'Our Southern Friend | Pioneer Personal Story | AA',
        'desc' => 'A minister\'s son and Southern farmer finds his way to God and sobriety.',
        'keywords' => 'our southern friend, Fitz M, pioneer story',
    ],
    'stories-edition-2/jims-story' => [
        'fileName' => 'stories2/stories2_31.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Jim’s Story'],
        'title' => 'Jim’s Story | First African American Group in AA',
        'desc' => 'The physician who originated A.A.\'s first group for colored members tells of his release.',
        'keywords' => 'jims story, diversity in AA, first black group',
    ],
    'stories-edition-2/promoted-to-chronic' => [
        'fileName' => 'stories2/stories2_32.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Promoted To Chronic'],
        'title' => 'Promoted To Chronic | 2nd Edition Personal Stories',
        'desc' => 'A career girl\'s journey from solitary blackout drinking to finding A.A.',
        'keywords' => 'promoted to chronic, career girl, solitary drinking',
    ],
    'stories-edition-2/the-prisoner-freed' => [
        'fileName' => 'stories2/stories2_33.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Prisoner Freed'],
        'title' => 'The Prisoner Freed | AA in Prisons Story',
        'desc' => 'After twenty years in prison, he finds that A.A. is the key to staying out.',
        'keywords' => 'prisoner freed, AA in prison, murder conviction recovery',
    ],
    'stories-edition-2/theres-nothing-the-matter-with-me' => [
        'fileName' => 'stories2/stories2_34.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'There’s Nothing The Matter With Me!'],
        'title' => 'There’s Nothing The Matter With Me! | AA Stories',
        'desc' => 'The denial of a man hocking his shoes for \'Sneaky Pete\' and his ultimate recovery.',
        'keywords' => 'nothing the matter, sneaky pete, rock bottom denial',
    ],
    'stories-edition-2/desperation-drinking' => [
        'fileName' => 'stories2/stories2_35.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Desperation Drinking'],
        'title' => 'Desperation Drinking | 2nd Edition Personal Stories',
        'desc' => 'Drinking to hold onto his job and sanity until he found A.A.',
        'keywords' => 'desperation drinking, maintaining sanity, AA stories',
    ],
    'stories-edition-2/annie-the-cop-fighter' => [
        'fileName' => 'stories2/stories2_36.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Annie The Cop Fighter'],
        'title' => 'Annie The Cop Fighter | 2nd Edition Personal Stories',
        'desc' => 'For 35 years she fought everyone and everything to stay drunk.',
        'keywords' => 'annie the cop fighter, female alcoholic, low bottom',
    ],
    'stories-edition-2/the-career-officer' => [
        'fileName' => 'stories2/stories2_37.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Career Officer'],
        'title' => 'The Career Officer | British Officer\'s Recovery',
        'desc' => 'An Irish officer in the British army finds sobriety after being \'retired\' by brandy.',
        'keywords' => 'career officer, military AA, Irish member',
    ],
    'stories-edition-2/the-independent-blonde' => [
        'fileName' => 'stories2/stories2_38.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'The Independent Blonde'],
        'title' => 'The Independent Blonde | 2nd Edition Personal Stories',
        'desc' => 'A self-sufficient lady\'s descent into psychopathic wards and her recovery.',
        'keywords' => 'independent blonde, psychopathic ward, women in AA',
    ],
    'stories-edition-2/he-who-loses-his-life' => [
        'fileName' => 'stories2/stories2_39.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'He Who Loses His Life'],
        'title' => 'He Who Loses His Life | Playwright\'s AA Story',
        'desc' => 'An ambitious playwright learns to find himself by losing himself in A.A.',
        'keywords' => 'loses his life, playwright, suicidal drinking',
    ],
    'stories-edition-2/freedom-from-bondage' => [
        'fileName' => 'stories2/stories2_40.html',
        'breadcrumb' => ['AA Literature', 'AA Big Book', 'Stories Edition 2', 'Freedom From Bondage'],
        'title' => 'Freedom From Bondage | 2nd Edition Personal Stories',
        'desc' => 'Discovering that drinking was the result of deeper defects and finding freedom.',
        'keywords' => 'freedom from bondage, character defects, spiritual healing',
    ],
    'prayers/morning-prayer' => [
        'fileName' => 'prayers/morning.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Morning Prayer'],
        'title' => 'Morning Prayer | Step 11 AA Prayer',
        'desc' => 'A prayer to ask God to direct our thinking and divorce it from self-pity and dishonesty.',
        'keywords' => 'aa morning prayer, page 86 prayer, step 11 aa',
    ],
    'prayers/nightly-prayer' => [
        'fileName' => 'prayers/nightly.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Nightly Prayer'],
        'title' => 'Nightly Prayer | AA Evening Reflection',
        'desc' => 'A prayer for the conclusion of the day, seeking forgiveness and freedom from worry.',
        'keywords' => 'aa nightly prayer, evening review, page 86',
    ],
    'prayers/third-step-prayer' => [
        'fileName' => 'prayers/3rdstep.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Third Step Prayer'],
        'title' => 'Third Step Prayer | AA Big Book Page 63',
        'desc' => 'The foundational prayer of surrender and offering oneself to a Higher Power.',
        'keywords' => '3rd step prayer, page 63, aa surrender prayer',
    ],
    'prayers/seventh-step-prayer' => [
        'fileName' => 'prayers/7thstep.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Seventh Step Prayer'],
        'title' => 'Seventh Step Prayer | AA Big Book Page 76',
        'desc' => 'A prayer for the removal of character defects and shortcomings.',
        'keywords' => '7th step prayer, character defects, page 76',
    ],
    'prayers/eleventh-step-prayer' => [
        'fileName' => 'prayers/11thstep.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Eleventh Step Prayer'],
        'title' => 'Eleventh Step Prayer | Prayer of St. Francis',
        'desc' => 'The prayer for peace and self-forgetting often used in Step 11 meditation.',
        'keywords' => '11th step prayer, st francis prayer, aa meditation',
    ],
    'prayers/lords-prayer' => [
        'fileName' => 'prayers/lordsprayer.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'The Lord\'s Prayer'],
        'title' => 'The Lord\'s Prayer | AA Meeting Closings',
        'desc' => 'The traditional prayer often used to close Alcoholics Anonymous meetings.',
        'keywords' => 'lords prayer, aa closing prayer, our father',
    ],
    'prayers/fear-prayer' => [
        'fileName' => 'prayers/fear.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Fear Prayer'],
        'title' => 'The Fear Prayer | AA Big Book Page 68',
        'desc' => 'A short prayer to remove fear and redirect attention to what God would have us be.',
        'keywords' => 'aa fear prayer, page 68, removing fear',
    ],
    'prayers/serenity-prayer' => [
        'fileName' => 'prayers/serenity-prayer.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Serenity Prayer'],
        'title' => 'Serenity Prayer | AA Foundational Prayer',
        'desc' => 'The classic prayer for serenity, courage, and wisdom in recovery.',
        'keywords' => 'serenity prayer, acceptance, courage to change',
    ],
    'prayers/serenity-prayer-extended' => [
        'fileName' => 'prayers/serenity_ex.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Serenity Prayer Extended'],
        'title' => 'Serenity Prayer Extended | Full Version',
        'desc' => 'The full version of the Serenity Prayer including the meditation on living one day at a time.',
        'keywords' => 'extended serenity prayer, full serenity prayer, one day at a time',
    ],
    'prayers/resentment-prayer' => [
        'fileName' => 'prayers/resentment.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Resentment Prayer'],
        'title' => 'Resentment Prayer | AA Freedom from Anger',
        'desc' => 'A prayer to help master resentments and show tolerance toward others.',
        'keywords' => 'aa resentment prayer, freedom from anger, sick man prayer',
    ],
    'prayers/st-francis-instrument' => [
        'fileName' => 'prayers/st_francis_instrument.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'Peace Prayer of St. Francis of Assisi'],
        'title' => 'Peace Prayer of St. Francis | Instrument of Peace',
        'desc' => 'A prayer focused on sowing love, pardon, and light to become an instrument of peace.',
        'keywords' => 'st francis, peace prayer, instrument of peace, sowing love',
    ],
    'readings/how-it-works' => [
        'fileName' => 'readings/howitworks.html',
        'breadcrumb' => ['AA Literature', 'Readings', 'How It Works'],
        'title' => 'How It Works | The Twelve Steps of AA',
        'desc' => 'The foundational reading of the AA program, outlining the path to recovery and the Twelve Steps.',
        'keywords' => 'how it works, aa twelve steps, program of recovery, big book page 58',
    ],
    'readings/the-promises' => [
        'fileName' => 'readings/promises.html',
        'breadcrumb' => ['AA Literature', 'Readings', 'The Promises'],
        'title' => 'The AA Promises | Ninth Step Promises',
        'desc' => 'Discover the 12 promises of Alcoholics Anonymous found in the Big Book on pages 83 and 84.',
        'keywords' => 'aa promises, 9th step promises, page 83 promises, serenity',
    ],
    'readings/aa-preamble' => [
        'fileName' => 'readings/preamble.html',
        'breadcrumb' => ['AA Literature', 'Readings', 'AA Preamble'],
        'title' => 'The AA Preamble | Fellowship Definition',
        'desc' => 'The official definition of Alcoholics Anonymous, its purpose, and the requirement for membership.',
        'keywords' => 'aa preamble, primary purpose, aa fellowship, membership requirement',
    ],
    'readings/twelve-traditions' => [
        'fileName' => 'readings/traditions.html',
        'breadcrumb' => ['AA Literature', 'Readings', 'Twelve Traditions'],
        'title' => 'The Twelve Traditions | AA Unity & Service',
        'desc' => 'The principles that ensure the unity and survival of Alcoholics Anonymous groups worldwide.',
        'keywords' => 'twelve traditions, aa unity, anonymity, group conscience',
    ],
    'readings/just-for-today' => [
        'fileName' => 'readings/justfortoday.html',
        'breadcrumb' => ['AA Literature', 'Readings', 'Just For Today'],
        'title' => 'Just For Today | Daily Recovery Reflection',
        'desc' => 'A powerful daily commitment to living life one day at a time in sobriety.',
        'keywords' => 'just for today, daily reflection, one day at a time, aa commitment',
    ],
    'readings/on-awakening' => [
        'fileName' => 'readings/onawakening.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'On Awakening'],
        'title' => 'On Awakening | AA Morning Meditation & Prayer',
        'desc' => 'The Big Book\'s suggested morning meditation for directing our thinking and plans for the day.',
        'keywords' => 'on awakening, aa morning meditation, page 86, daily reprieve',
    ],
    'readings/on-retiring' => [
        'fileName' => 'readings/onretiring.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'On Retiring'],
        'title' => 'On Retiring | AA Nightly Review',
        'desc' => 'The Big Book checklist for constructively reviewing our day before sleep.',
        'keywords' => 'on retiring, aa evening review, inventory, page 86',
    ],
    'readings/a-vision-for-you' => [
        'fileName' => 'readings/avisionforyou.html',
        'breadcrumb' => ['AA Literature', 'Prayers', 'A Vision For You'],
        'title' => 'A Vision For You | AA Fellowship Reflection',
        'desc' => 'The Chilling Vapor of Loneliness and the substitute found in the AA fellowship.',
        'keywords' => 'a vision for you, page 151, aa fellowship, miracles',
    ],
];
